project:
  type: website

website:
  title: "oooo12"
  site-url: https://oooo12.netlify.app
  description: "데이터, 통계"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: rss
        href: index.xml

format:
  html:
    theme: 
    - lux
    - custom.scss
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css

editor: visual
execute:
  freeze: auto

