project:
  type: website

website:
  title: "oooo12"
  favicon: favicon.png
  site-url: https://oooo12.netlify.app
  description: "데이터, 통계"
  search:
    type: textbox
  sidebar: 
    style: "docked"
    title: "oooo12"
    tools:
      - icon : github
        href: https://github.com/oooo12-git
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/oooo12
      - icon : instagram
        text: Instagram
        href: https://www.instagram.com/jaahyunssi/
    logo: profile.png
    pinned: true
    contents: /*
    
  page-footer: 
    left: "Copyright 2023, Jaa Hyun Kim" 
    right: 
      - icon : github
        href: https://github.com/oooo12-git
      - icon: linkedin
        href: https://www.linkedin.com/in/oooo12
      - icon : instagram
        href: https://www.instagram.com/jaahyunssi/

format:
  html:
    mainfont: Josefin Sans
    fontsize: 1.1em
    linestretch: 1.7
    grid: 
      sidebar-width: 300px
      body-width: 800px
      margin-width: 300px
      gutter-width: 1.5em
    toc: true

editor: visual
execute:
  freeze: auto

